### ISSUE TITLE
Error help please [FIXED]

### ISSUE THREAD

**Issue by heafun** [aioobe/cloudconvert#2]
CloudConvertService service = new CloudConvertService("<My Apikey>");

     ConvertProcess process = null;
	try {
		process = service.startProcess("webm", "mp3");
	} catch (URISyntaxException e2) {
		e2.printStackTrace();
	}
     try {
		process.startConversion(new File("C:/Users/Marc/Desktop/Testdownloads/Azad - Special (Prod. by Patrick Collier).webm"));
	} catch (FileNotFoundException e1) {
		e1.printStackTrace();
	} catch (ParseException e1) {
		e1.printStackTrace();
	}
     ProcessStatus status;
     waitLoop: while (true) {
         status = process.getStatus();
         switch (status.step) {
         case FINISHED: break waitLoop;
         case ERROR: throw new RuntimeException(status.message);
         }
         try {
			Thread.sleep(200);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
     }
     try {
		service.download(status.output.url, new File("C:/Users/Marc/Desktop/Testdownloads/output.mp3"));
	} catch (IOException e) {
		e.printStackTrace();
	}
     process.delete();

Gives me following Error how can I fix it?:

Exception in thread "main" javax.ws.rs.ForbiddenException: HTTP 403 Forbidden
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:942)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:784)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:672)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:668)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:327)
	at org.aioobe.cloudconvert.CloudConvertService.startProcess(CloudConvertService.java:29)
	at Test.main(Test.java:212)

**Comment by TylerBrignone** [comment]
I am having this same error, what did you do to fix it?
