### ISSUE TITLE
Error when testing

### ISSUE THREAD

**Issue by AchileB3** [aioobe/cloudconvert#9]
Hello, i am having this error on command line when i execute the example in the read me. 
Exception in thread "main" javax.ws.rs.ForbiddenException: HTTP 403 Forbidden
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:942)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:784)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:672)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:668)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:327)
	at org.aioobe.cloudconvert.CloudConvertService.startProcess(CloudConvertService.java:34)
	at org.intelligentsia.monitoring.svfe.atm.controllers.Test.main(Test.java:22)

**Comment by aioobe** [comment]
Did you replace `<api key>` with a valid API key?

**Comment by AchileB3** [comment]
Thanks for replying. Yes i did. The problem seems to be on api, because i changed to API V1 and i finaly performed the conversion. Now my question is, how can generate a valid key for API V2?
